language: python

python:
  - '3.3'
  - '3.4'
  - 'nightly'

before_install:
  - sudo apt-get update
  - sudo apt-get install -qq python3-gi gir1.2-gtk-3.0 gir1.2-networkmanager-1.0

virtualenv:
  system_site_packages: true

install:
  - pip3 install -r requirements.txt

script:
  - ./run-tests
