# Run unit tests script

name: Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4

    # The minimum supported Python version is actually 3.8, but it's not
    # available on GitHub's ubuntu-24.04 images.
    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: "3.9"

    # Note: we could try and cache the pre-commit environment
    # See the pre-commit docs at https://pre-commit.com/#github-actions-example
    - name: Run pre-commit hooks
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
        pre-commit run --all-files

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt-get update
        sudo apt install -y meson gettext itstool libgirepository1.0-dev gir1.2-gtk-4.0 libgtksourceview-5-dev libportal-dev
        pip install --user pytest pycairo PyGObject==3.50.0 caldav lxml

    - name: Build and install GTG
      run: |
        meson setup --prefix=${PWD}/inst ./build
        cd build
        meson compile
        sudo meson install

    - name: Run unit tests with Pytest
      run: |
        export PYTHONPATH=${PWD}/inst/lib/python3.9/site-packages
        # Provide a fake display server, for tests that need one
        xvfb-run pytest
